---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{.Enrichment.Name}}
  labels:
    project: dracon
spec:
  inputs: {resources: [
    {{.Enrichment.InResources "bandit" "gosec"}}
  ]}
  outputs: {resources: [{name: {{.Enrichment.OutResource}}, type: storage}]}
  steps:
  - {{.Enrichment.StepSetup}}
  # run enricher
  - name: run-enricher
    image: dracon/enrichment:latest
    imagePullPolicy: Never
    env:
    - name: ENRICHER_READ_PATH
      value: /workspace
    - name: ENRICHER_WRITE_PATH
      value: {{.Enrichment.OutPath}}
    - name: ENRICHER_DB_CONNECTION
      value: "postgresql://dracon:dracon@dracon-enrichment-db?sslmode=disable"
    command: ["/enricher"]
