---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{.Enrichment.Name}}
spec:
  inputs: {resources: [
    {{.Enrichment.InResources "bandit" "gosec"}}
  ]}
  outputs: {resources: [{name: {{.Enrichment.OutResource}}, type: storage}]}
  steps:
  - {{.Enrichment.StepSetup}}
  # run enricher
  - name: run-enricher
    image: dracon/enrichment:latest
    imagePullPolicy: Never
    env:
    - name: DRACON_READ_LOCATION
      value: /workspace
    - name: DRACON_WRITE_LOCATION
      value: {{.Enrichment.OutPath}}
    - name: DRACON_ENRICHMENT_DB_URI
      value: "postgresql://dracon:dracon@dracon-enrichment-db"
    command: ["sh"]
    args: ["-c",
      "python3 -u /home/app/dracon/enrichment_service/enrich_service.py --setup"
    ]
