---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{.Producer.Name "gosec"}}
  labels:
    project: dracon
spec:
  inputs: {resources: [{{.Producer.InResource}}]}
  outputs: {resources: [{{.Producer.OutResource}}]}
  volumes: [{{.Producer.SpecVolume}}]
  steps:
  - {{.Producer.StepSetup}}
  # run gosec
  - name: run-gosec
    image: securego/gosec
    command: ["sh"]
    args: ["-c",
      "gosec -fmt=json -out={{.Producer.ToolOutPath}} {{.Producer.SourcePath}}/... || true"
    ]
    {{.Producer.StepExtras}}
  # parse results
  - name: parse-gosec
    image: dracon/producer/gosec
    imagePullPolicy: Never
    command: ["/parse"]
    args: [
      "-in={{.Producer.ToolOutPath}}",
      "-out={{.Producer.OutPath}}"
    ]
    {{.Producer.StepExtras}}
