---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{.Pipeline.Name "demo"}}
spec:
  params: [{{.Pipeline.Params}}]
  resources:
  - {type: git, name: git-source}
  - {{.Pipeline.ProducerResources "bandit" "gosec"}}
  - {{.Pipeline.SourceResource}}
  - {{.Pipeline.EnricherResource}}
  tasks:
  # stage 1 - archive source
  - name: fetch-source
    taskRef: {name: git-source}
    resources:
      inputs: [{name: git-source, resource: git-source}]
      outputs: [{{.Pipeline.TaskSourceResource}}]
  # stage 2 - run tools
  - name: bandit-producer
    runAfter: [fetch-source]
    taskRef: {name: {{.Producer.Name "bandit"}}}
    resources:
      inputs: [{{.Pipeline.TaskSourceResource}}]
      outputs: [{{.Pipeline.TaskProducerOutResource "bandit"}}]
  - name: gosec-producer
    runAfter: [fetch-source]
    taskRef: {name: {{.Producer.Name "gosec"}}}
    resources:
      inputs: [{{.Pipeline.TaskSourceResource}}]
      outputs: [{{.Pipeline.TaskProducerOutResource "gosec"}}]
  # - name: spotbugs-producer
  #   runAfter: [fetch-source]
  #   taskRef: {name: {{.Producer.Name "spotbugs"}}}
  #   resources:
  #     inputs: [{{.Pipeline.TaskSourceResource}}]
  #     outputs: [{{.Pipeline.TaskProducerOutResource "spotbugs"}}]
  # stage 3 - enrichment
  - name: enricher
    runAfter: [bandit-producer, gosec-producer]
    taskRef: {name: {{.Enrichment.Name}}}
    resources:
      inputs: [{{.Pipeline.TaskEnricherInputResources "bandit" "gosec"}}]
      outputs: [{{.Pipeline.TaskEnricherOutResource}}]
  # stage 4 - consumers
  - name: elasticsearch-consumer
    runAfter: [enricher]
    taskRef: {name: {{.Consumer.Name "elasticsearch"}}}
    params: [{{.Pipeline.ConsumerParams}}]
    resources:
      inputs: [{{.Pipeline.TaskEnricherOutResource}}]
      outputs: []
