---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: {{.Producer.Name "spotbugs"}}
spec:
  inputs: {resources: [{{.Producer.InResource}}]}
  outputs: {resources: [{{.Producer.OutResource}}]}
  volumes: [{{.Producer.SpecVolume}}]
  steps:
  - {{.Producer.StepSetup}}
  # run spotbugs
  - name: run-spotbugs
    image: dracon/spotbugs:latest
    imagePullPolicy: Never
    command: ["sh"]
    args: [ "-c",
      "spotbugs {{.Producer.SourcePath}} -output {{.Producer.ToolOutPath}} -xml:withMessages"
    ]
    {{.Producer.StepExtras}}
  # parse results
  - name: parse-spotbugs
    image: dracon/producer/spotbugs:latest
    imagePullPolicy: Never
    command: ["/parse"]
    args: [
      "-in={{.Producer.ToolOutPath}}",
      "-out={{.Producer.OutPath}}"
    ]
    {{.Producer.StepExtras}}
