---
# source archive
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.SourceID}}}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/{{.PipelineResource.SourceID}}}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# bandit out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.ProducerID "bandit"}}}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/{{.PipelineResource.ProducerID "bandit"}}}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# gosec out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.ProducerID "gosec"}}}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/{{.PipelineResource.ProducerID "gosec"}}}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# spotbugs out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.ProducerID "spotbugs"}}}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/{{.PipelineResource.ProducerID "spotbugs"}}}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# enricher out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.EnricherID}}}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/{{.PipelineResource.EnricherID}}}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# git+ssh config: service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitssh-github-tektoncd-pipeline
secrets:
- name: gitssh-github-tektoncd-pipeline
---
# git+ssh config: pipeline resource
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: {{.PipelineResource.ID "gitssh-github-tektoncd-pipeline" }}}
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: git@github.com:tektoncd/pipeline.git
---
# pipelinerun
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: {{.PipelineRun.Name "demo"}}
spec:
  pipelineRef: {name: {{.Pipeline.Name "demo"}}}
  params: [
    {{.PipelineRun.Params}}
  ]
  podTemplate: {}
  serviceAccount: gitssh-github-tektoncd-pipeline # replace with desired git source service account (if needed)
  resources:
  - {name: git-source, resourceRef: {name: {{.PipelineResource.ID "gitssh-github-tektoncd-pipeline" }}}} # replace with desired git source
  - {{.PipelineRun.ResourceSource}}
  - {{.PipelineRun.ResourceProducers "bandit" "gosec"}}
  - {{.PipelineRun.ResourceEnricher}}
  timeout: 1h0m0s
