---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dracon-elasticsearch-consumer
spec:
  inputs: {resources: [{name: enricher-out, type: storage}]}
  steps:
  # run elasticsearch consumer
  - name: run-elasticsearch-consumer
    image: dracon/consumer/elasticsearch:latest
    imagePullPolicy: Never
    env:
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch-logging.kube-system:9200
    command: ["/consume"]
    args: [
      "-in", "/workspace/enricher-out/",
      "-es-index", "dracon",
    ]
