---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dracon-enrichment
spec:
  inputs: {resources: [
    {name: bandit-out, type: storage},
    {name: gosec-out, type: storage},
    # {name: spotbugs-out, type: storage},
  ]}
  outputs: {resources: [{name: enricher-out, type: storage}]}
  steps:
  # update permissions
  - name: setup-permissions
    image: busybox:latest
    command: ["chown"]
    args: ["-R", "1000:1000", "/workspace/output/enricher-out"]
  # run enricher
  - name: run-enricher
    image: dracon/enrichment:latest
    imagePullPolicy: Never
    env:
    - name: DRACON_READ_LOCATION
      value: /workspace
    - name: DRACON_WRITE_LOCATION
      value: /workspace/output/enricher-out
    - name: DRACON_ENRICHMENT_DB_URI
      value: "postgresql://dracon:dracon@dracon-enrichment-db"
    command: ["sh"]
    args: ["-c",
      "python3 -u /home/app/dracon/enrichment_service/enrich_service.py --setup"
    ]
