---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: dracon-demo
spec:
  resources:
  - {type: git, name: git-source}
  - {type: storage, name: source-archive}
  - {type: storage, name: bandit-producer-out}
  - {type: storage, name: gosec-producer-out}
  # - {type: storage, name: spotbugs-producer-out}
  - {type: storage, name: enricher-out}
  tasks:
  # stage 1 - archive source
  - name: fetch-source
    taskRef: {name: dracon-source}
    resources:
      inputs: [{name: git-source, resource: git-source}]
      outputs: [{name: source, resource: source-archive}]
  # stage 2 - run tools
  - name: bandit-producer
    runAfter: [fetch-source]
    taskRef: {name: dracon-bandit-producer}
    resources:
      inputs: [{name: source, resource: source-archive}]
      outputs: [{name: producer-out, resource: bandit-producer-out}]
  - name: gosec-producer
    runAfter: [fetch-source]
    taskRef: {name: dracon-gosec-producer}
    resources:
      inputs: [{name: source, resource: source-archive}]
      outputs: [{name: producer-out, resource: gosec-producer-out}]
  # - name: spotbugs-producer
  #   runAfter: [fetch-source]
  #   taskRef: {name: dracon-spotbugs-producer}
  #   resources:
  #     inputs: [{name: source, resource: source-archive}]
  #     outputs: [{name: producer-out, resource: spotbugs-producer-out}]
  # stage 3 - enrichment
  - name: enricher
    runAfter: [bandit-producer, gosec-producer]
    taskRef: {name: dracon-enrichment}
    resources:
      inputs: [
        {name: bandit-out, resource: bandit-producer-out},
        {name: gosec-out, resource: gosec-producer-out},
        # {name: spotbugs-out, resource: spotbugs-producer-out},
      ]
      outputs: [{name: enricher-out, resource: enricher-out}]
  # stage 4 - consumers
  - name: elasticsearch-consumer
    runAfter: [enricher]
    taskRef: {name: dracon-elasticsearch-consumer}
    resources:
      inputs: [{name: enricher-out, resource: enricher-out}]
      outputs: []
