---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-github-thoughtmachine-please
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/thought-machine/please.git
