---
# source archive
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: dracon-source-archive}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/source}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# bandit out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: dracon-bandit-producer-out}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/tool/bandit}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# gosec out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: dracon-gosec-producer-out}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/tool/gosec}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# spotbugs out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: dracon-spotbugs-producer-out}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/tool/spotbugs}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
# enricher out
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata: {name: dracon-enricher-out}
spec:
  type: storage
  params: [{name: location, value: s3://dracon/enricher}, {name: type, value: gcs}, {name: dir, value: "y"}]
  secrets: [{fieldName: BOTO_CONFIG, secretName: dracon-storage, secretKey: boto_config}]
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: dracon-demo-run
spec:
  pipelineRef: {name: dracon-demo}
  podTemplate: {}
  # serviceAccount: git-github-thoughtmachine-please # replace with desired git source service account (if needed)
  resources:
  - {name: git-source, resourceRef: {name: git-github-thoughtmachine-please}} # replace with desired git source
  - {name: source-archive, resourceRef: {name: dracon-source-archive}}
  - {name: bandit-producer-out, resourceRef: {name: dracon-bandit-producer-out}}
  # - {name: spotbugs-producer-out, resourceRef: {name: dracon-spotbugs-producer-out}}
  - {name: gosec-producer-out, resourceRef: {name: dracon-gosec-producer-out}}
  - {name: enricher-out, resourceRef: {name: dracon-enricher-out}}
  timeout: 1h0m0s
