apiVersion: v1
kind: Namespace
metadata:
  name: dracon

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dracon-db
  namespace: dracon
  labels:
    app: dracon-db
    project: dracon
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: dracon-db
      project: dracon
  template:
    metadata:
      labels:
        app: dracon-db
        project: dracon
    spec:
      containers:
        - name: dracon-db
          image: postgres:11-alpine
          env:
            - name: POSTGRES_USER
              value: dracon
            - name: POSTGRES_PASSWORD
              value: dracon
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 5Gi
              cpu: 1
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: dracon-db
  namespace: dracon
  labels:
    project: dracon
spec:
  ports:
    - port: 5432
  selector:
    app: dracon-db

---
