---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dracon-gosec-producer
spec:
  inputs: {resources: [{name: source, type: storage}]}
  outputs: {resources: [{name: producer-out, type: storage}]}
  volumes: [{emptyDir: {}, name: dracon-ws}]
  steps:
  # extract source and setup
  - name: extract-source
    image: busybox:latest
    command: ["sh"]
    args: ["-c",
      "mkdir -p /dracon/source && tar -C /dracon/source -xzf /workspace/source/source.tgz && chown -R 1000:1000 /workspace/output/producer-out /dracon"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
  - name: run-gosec
    image: securego/gosec
    command: ["sh"]
    args: ["-c",
      "gosec -fmt=json -out=/dracon/results.json /dracon/source/... || true"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
  - name: parse-gosec
    image: dracon/producer/gosec
    imagePullPolicy: Never
    command: ["/parse"]
    args: [
      "-in=/dracon/results.json",
      "-out=/workspace/output/producer-out/results.pb"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
