---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dracon-spotbugs-producer
spec:
  inputs: {resources: [{name: source, type: storage}]}
  outputs: {resources: [{name: producer-out, type: storage}]}
  volumes: [{emptyDir: {}, name: dracon-ws}]
  steps:
  # extract source and setup
  - name: extract-source
    image: busybox:latest
    command: ["sh"]
    args: ["-c",
      "mkdir -p /dracon/source && tar -C /dracon/source -xzf /workspace/source/source.tgz && chown -R 1000:1000 /workspace/output/producer-out /dracon"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
  # run spotbugs
  - name: run-spotbugs
    image: dracon/spotbugs:latest
    imagePullPolicy: Never
    command: ["sh"]
    args: [ "-c",
      "spotbugs /dracon/source -output /dracon/results.xml -xml:withMessages"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
  # parse results
  - name: parse-spotbugs
    image: dracon/producer/spotbugs:latest
    imagePullPolicy: Never
    command: ["/parse"]
    args: [
      "-in=/dracon/results.xml",
      "-out=/workspace/output/producer-out/results.pb"
    ]
    volumeMounts: [{mountPath: /dracon, name: dracon-ws}]
